# DigitalOcean App Platform specification
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
#
# Usage:
#   doctl apps create --spec .do/app.yaml
#   — or — paste this into the App Platform dashboard's YAML editor.

name: edupay-system
region: nyc   # change to: ams, sfo, sgp, lon, fra, tor, blr, syd

# ── Web Service ──────────────────────────────────────────────────────────────
services:
  - name: web
    github:
      repo: balirwaalvin/EduPay-System
      branch: main
      deploy_on_push: true

    # Build & run
    build_command: npm install --production
    run_command: npm start
    environment_slug: node-js

    # Scaling
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb   # cheapest tier; upgrade as needed

    # DigitalOcean injects PORT automatically; Express already reads process.env.PORT
    http_port: 8080

    # Environment variables
    envs:
      - key: NODE_ENV
        value: "production"
        scope: RUN_TIME

      - key: JWT_SECRET
        # ← Set the actual value in the App Platform dashboard under Environment Variables
        scope: RUN_TIME
        type: SECRET

      # Bind DATABASE_URL from the managed DB component named "db" (no hyphens).
      # Component names with hyphens break DO's ${} interpolation.
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME

    # Health check
    health_check:
      http_path: /

# ── Managed PostgreSQL Database ──────────────────────────────────────────────
databases:
  - name: db
    engine: PG
    version: "16"
    # Use db-s-1vcpu-1gb for production; dev database has known networking limits
    size: db-s-1vcpu-1gb
    num_nodes: 1
