# DigitalOcean App Platform specification
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
#
# Usage:
#   doctl apps create --spec .do/app.yaml
#   — or — paste this into the App Platform dashboard's YAML editor.

name: edupay-system
region: nyc   # change to: ams, sfo, sgp, lon, fra, tor, blr, syd

# ── Web Service ──────────────────────────────────────────────────────────────
services:
  - name: web
    github:
      repo: balirwaalvin/EduPay-System
      branch: main
      deploy_on_push: true

    # Build & run
    build_command: npm install --production
    run_command: npm start
    environment_slug: node-js

    # Scaling
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb   # cheapest tier; upgrade as needed

    # DigitalOcean injects PORT automatically; Express already reads process.env.PORT
    http_port: 8080

    # Environment variables
    envs:
      - key: NODE_ENV
        value: "production"
        scope: RUN_TIME

      - key: JWT_SECRET
        # Set this value in the App Platform dashboard → Environment Variables
        scope: RUN_TIME
        type: SECRET

      # DATABASE_URL must be set manually in the dashboard:
      # App → Settings → Environment Variables → add DATABASE_URL
      # Get the value from: Databases → edupay-db → Connection Details → URI

    # Health check
    health_check:
      http_path: /

# ── Managed PostgreSQL Database ──────────────────────────────────────────────
databases:
  - name: edupay-db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb   # dedicated instance — resolves to a real hostname (not 'base')
    num_nodes: 1
